# Generated by Django 5.2.8 on 2025-11-20 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_aadhaarverification_admin_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='verified_at',
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
