# Generated by Django 5.2.8 on 2025-11-20 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_remove_aadhaarverification_admin_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trustedcontact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trustedcontact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='user',
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/'),
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/'),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='rc_image',
            field=models.ImageField(upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='vehicle_model',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('home_location', models.CharField(blank=True, max_length=255, null=True)),
                ('work_location', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aadhaarverification',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_verification', to='profile_app.profile'),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to='profile_app.profile'),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='profile_app.profile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
