# Generated by Django 5.2.8 on 2025-11-21 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_alter_aadhaarverification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaarverification',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_verification', to='profile_app.profile'),
        ),
    ]
