# Generated by Django 4.2.7 on 2025-11-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_alter_aadhaarverification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaarverification',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_verification', to='profile_app.profile'),
        ),
    ]
