# Generated by Django 5.2.8 on 2025-12-08 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_alter_aadhaarverification_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhaarverification',
            old_name='is_verified',
            new_name='verified',
        ),
        migrations.RenameField(
            model_name='trustedcontact',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='vehicledetails',
            old_name='vehicle_model',
            new_name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='front_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='home_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_location',
        ),
        migrations.RemoveField(
            model_name='trustedcontact',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='rc_image',
        ),
        migrations.AddField(
            model_name='aadhaarverification',
            name='aadhaar_number',
            field=models.CharField(default=' ', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InviteFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='profile_app.profile')),
            ],
        ),
    ]
