# Generated by Django 4.2.7 on 2025-11-19 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20)),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('mode_of_travel', models.CharField(blank=True, choices=[('walk', 'Walking'), ('bike', 'Bicycle'), ('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('metro', 'Metro'), ('auto', 'Auto Rickshaw'), ('bike_taxi', 'Bike Taxi'), ('other', 'Other')], max_length=20, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('trip_purpose', models.CharField(blank=True, choices=[('work', 'Work/Office'), ('education', 'Education'), ('shopping', 'Shopping'), ('social', 'Social/Recreation'), ('medical', 'Medical'), ('personal', 'Personal Business'), ('other', 'Other')], max_length=50, null=True)),
                ('number_of_companions', models.IntegerField(default=0)),
                ('ticket_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('toll_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parking_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('co2_emission_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_manual_entry', models.BooleanField(default=False, help_text='True if trip was manually entered')),
                ('route_polyline', models.TextField(blank=True, help_text='Encoded polyline from Google Directions API', null=True)),
                ('suggested_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from Google Directions API', max_digits=10, null=True)),
                ('suggested_duration_minutes', models.IntegerField(blank=True, help_text='Duration from Google Directions API', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(help_text="User's notes about the trip")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(help_text='GPS accuracy in meters')),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='trips.trip')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='trips_tripl_trip_id_25e17b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', '-start_time'], name='trips_trip_user_id_fa96ee_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'),
        ),
    ]
