# Generated by Django 5.2.8 on 2025-11-21 01:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_plannedtrip_tripsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripsession',
            name='planned_trip',
        ),
        migrations.AlterModelOptions(
            name='plannedtrip',
            options={'ordering': ['-planned_start_date']},
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='start_location',
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='title',
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='actual_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_trip', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='destination_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='destination_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='estimated_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='estimated_duration_minutes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='mode_of_travel',
            field=models.CharField(blank=True, choices=[('walk', 'Walking'), ('bike', 'Bicycle'), ('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('metro', 'Metro'), ('auto', 'Auto Rickshaw'), ('bike_taxi', 'Bike Taxi'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='number_of_companions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='planned_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='planned_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='route_polyline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='start_location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='start_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='trip_name',
            field=models.CharField(default='Untitled Trip', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='trip_purpose',
            field=models.CharField(blank=True, choices=[('work', 'Work/Office'), ('education', 'Education'), ('shopping', 'Shopping'), ('social', 'Social/Recreation'), ('medical', 'Medical'), ('personal', 'Personal Business'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='waypoints',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedtrip',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedtrip',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.AddIndex(
            model_name='plannedtrip',
            index=models.Index(fields=['user', 'status'], name='trips_plann_user_id_133931_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedtrip',
            index=models.Index(fields=['planned_start_date'], name='trips_plann_planned_9b3431_idx'),
        ),
        migrations.DeleteModel(
            name='TripSession',
        ),
    ]
