# Generated by Django 5.2.8 on 2025-11-21 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_tripsession_planned_trip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'My Honda City'", max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('scooter', 'Scooter'), ('electric', 'Electric Vehicle')], max_length=50)),
                ('fuel_efficiency', models.FloatField(default=15.0, help_text='km per liter')),
                ('emissions_factor', models.FloatField(default=120.0, help_text='grams of CO2 per km')),
                ('fuel_price_per_liter', models.DecimalField(decimal_places=2, default=100.0, help_text='Current fuel price per liter', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Currently used vehicle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField(default=0)),
                ('total_distance', models.FloatField(default=0, help_text='in kilometers')),
                ('total_co2', models.FloatField(default=0, help_text='in grams')),
                ('total_fuel_cost', models.FloatField(default=0, help_text='in currency')),
                ('trips_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
