# Generated by Django 5.2.8 on 2025-12-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tripparticipant'),
    ]

    operations = [
    ]
