# Generated by Django 5.2.8 on 2025-12-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_add_creators_as_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripParticipant',
        ),
    ]
