# Generated by Django 5.2.8 on 2025-12-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_tripshare'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tripshare',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='tripshare',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='tripshare',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Companion',
        ),
        migrations.DeleteModel(
            name='TripShare',
        ),
    ]
